In [114]:
import pandas

df = pandas.read_csv("./1.3.csv", index_col="name")  # Monday's changes included
df

,years,genres,rating,description,stars,votes,run_time,directors
name,,,,,,,,
Blood Red Sky,(2021),"['Action', 'Horror', 'Thriller']",6.1,A woman with a mysterious illness is forced in...,"['Peri Baumeister', 'Carl Anton Koch', 'Alexan...","21,062",121.0,['Peter Thorwarth']
Masters of the Universe: Revelation,(2021– ),"['Animation', 'Action', 'Adventure']",5.0,The war for Eternia begins again in what may b...,"['Chris Wood', 'Sarah Michelle Gellar', 'Lena ...","17,870",25.0,[]
The Walking Dead,(2010–2022),"['Drama', 'Horror', 'Thriller']",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"['Andrew Lincoln', 'Norman Reedus', 'Melissa M...","885,805",44.0,[]
Rick and Morty,(2013– ),"['Animation', 'Adventure', 'Comedy']",9.2,An animated series that follows the exploits o...,"['Justin Roiland', 'Chris Parnell', 'Spencer G...","414,849",23.0,[]
Army of Thieves,(2021),"['Action', 'Crime', 'Horror']",NaN,"A prequel, set before the events of Army of th...","['Matthias Schweighöfer', 'Nathalie Emmanuel',...",0,NaN,['Matthias Schweighöfer']
...,...,...,...,...,...,...,...,...
The Imperfects,(2021– ),"['Adventure', 'Drama', 'Fantasy']",NaN,NaN,"['Morgan Taylor Campbell', 'Chris Cope', 'Iñak...",0,NaN,[]
Arcane,(2021– ),"['Animation', 'Action', 'Adventure']",NaN,NaN,[],0,NaN,[]
Heart of Invictus,(2022– ),"['Documentary', 'Sport']",NaN,NaN,['Prince Harry'],0,NaN,['Orlando von Einsiedel']
The Imperfects,(2021– ),"['Adventure', 'Drama', 'Fantasy']",NaN,NaN,"['Morgan Taylor Campbell', 'Iñaki Godoy', 'Rhi...",0,NaN,['Jovanka Vuckovic']
The Imperfects,(2021– ),"['Adventure', 'Drama', 'Fantasy']",NaN,NaN,"['Morgan Taylor Campbell', 'Jennifer Cheon Gar...",0,NaN,['Jovanka Vuckovic']

In [115]:
# Drop all rows that are completely identical
# Ignore the `description` column, we can't easily resolve those conflicts so only keep the first
df.drop_duplicates(
    inplace=True,
    keep="first",
    subset=[
        "years",
        "genres",
        "rating",
        "stars",
        "votes",
        "run_time",
        "directors",
    ],
)

In [116]:
# Count still-existing `name` duplicates
dupe_counts = df.index.value_counts()
print(dupe_counts[dupe_counts > 1].head(20))
print(sum(dupe_counts[dupe_counts > 1]))
# 60% of the data is duplicated what is this

 Bleach: Burîchi                       65
 Avatar: The Last Airbender            61
 Dexter                                48
 The Drew Barrymore Show               45
 Power Rangers Beast Morphers          38
 Johnny Test                           38
 She-Ra and the Princesses of Power    37
 The Boondocks                         30
 The Circle                            25
 7Seeds                                23
 Virgin River                          21
 Formula 1: Drive to Survive           20
 Never Have I Ever                     20
 La casa de las flores                 19
 Élite                                 19
 Dynasty                               19
 Glitch Techs                          18
 Supergirl                             18
 Riverdale                             18
 Queer Eye                             18
Name: name, dtype: int64
3043

In [117]:
df[df.index.duplicated(keep=False)].sort_index().head(20)

,years,genres,rating,description,stars,votes,run_time,directors
name,,,,,,,,
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",6.6,"The school goes into lockdown and Clay, Tony a...","['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,694",61.0,['Brenda Strong']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",6.1,The Jensens make the boys take a drug test. Wh...,"['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,507",57.0,['Brenda Strong']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",5.7,"After an incident at school, Clay thinks someo...","['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,597",58.0,['Russell Mulcahy']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",7.7,"Strengthened by the struggles they've endured,...","['Dylan Minnette', 'Grace Saif', 'Christian Na...","2,312",98.0,['Brian Yorkey']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",6.8,When the dean begins a new investigation and t...,"['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,640",60.0,['Tommy Lohmann']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",5.9,Clay's mental health continues to decline as t...,"['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,420",60.0,['Sunu Gonera']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",5.6,As the school gears up for the Love Is Love da...,"['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,635",59.0,['Michael Sucsy']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",5.1,Clay is forced to confront his anxiety on the ...,"['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,714",59.0,['Michael Sucsy']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",6.2,"In the wake of the lockdown, the school is on ...","['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,619",57.0,['Sunu Gonera']
13 Reasons Why,(2017–2020),"['Drama', 'Mystery', 'Thriller']",5.7,"The police question Tyler about the guns, leav...","['Dylan Minnette', 'Grace Saif', 'Christian Na...","1,798",59.0,['Russell Mulcahy']
1899,(2022– ),"['Drama', 'History', 'Horror']",NaN,NaN,"['Aneurin Barnard', 'Anton Lesser', 'Mathilde ...",0,NaN,['Baran bo Odar']
1899,(2022– ),"['Drama', 'History', 'Horror']",NaN,NaN,[],0,NaN,['Baran bo Odar']
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",7.9,"Left vulnerable after Omen's attack, the royal...","['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",143,22.0,['Andrew L. Schmidt']
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",8.6,"With the fate of the universe at stake, the ro...","['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",148,22.0,"['Rodrigo Blaas', 'Johane Matte']"
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",8.6,"After learning the location of Gaylen's Core, ...","['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",138,22.0,['Andrew L. Schmidt']
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",7.6,"Trolls, humans, gnomes and aliens alike all ma...",[],5,1.0,[]
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",8.5,With General Morando searching for Gaylen's Co...,"['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",142,22.0,['Rodrigo Blaas']
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",7.5,With General Morando's invasion of Earth immin...,"['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",136,22.0,['Elaine Bogan']
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",7.6,"Mother, the AI controlling the royals' ship, r...","['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",137,22.0,['Andrew L. Schmidt']
3Below: Tales of Arcadia,(2018–2019),"['Animation', 'Action', 'Adventure']",7.8,Colonel Kubritz stages a phony quarantine of A...,"['Tatiana Maslany', 'Diego Luna', 'Nick Offerm...",139,22.0,"['Elaine Bogan', 'Francisco Ruiz-Velasco']"

In [118]:
# Looks like many individual TV show episodes are included
# We can just leave those as-is
# We should bring back the numerical index if the name isn't going to be unique then
df.reset_index(inplace=True)

In [119]:
df["dupe_counts"] = df["name"].map(lambda name: dupe_counts[name])
duplicates = df[df["dupe_counts"] > 1]
duplicates.sort_values(["dupe_counts", "name"]).head(20)

,name,years,genres,rating,description,stars,votes,run_time,directors,dupe_counts
8937,1899,(2022– ),"['Drama', 'History', 'Horror']",NaN,NaN,"['Aneurin Barnard', 'Anton Lesser', 'Mathilde ...",0,NaN,['Baran bo Odar'],2
9308,1899,(2022– ),"['Drama', 'History', 'Horror']",NaN,NaN,[],0,NaN,['Baran bo Odar'],2
6328,American Experience,(1988– ),"['Documentary', 'Biography', 'History']",6.6,The personal development of George Washington ...,"['David McCullough', 'Robert Dawidoff', 'Thad ...",41,90.0,['David Sutherland'],2
6368,American Experience,(1988– ),"['Documentary', 'Biography', 'History']",6.8,"In 1931, Honolulu's tropical tranquility was s...","['Thalia Massie', 'Thomas Massie', 'Grace Hubb...",194,53.0,"['Mark Zwonitzer', 'Michael Chin']",2
9152,Bangkok Breaking,(2021– ),"['Action', 'Crime', 'Drama']",NaN,NaN,"['Sahajak Boonthanakit', 'Suda Chuenban', 'Daw...",0,NaN,['Kongkiat Khomsiri'],2
9153,Bangkok Breaking,(2021– ),"['Action', 'Crime', 'Drama']",NaN,NaN,[],0,NaN,['Kongkiat Khomsiri'],2
8977,Heartstopper,NaN,"['Drama', 'Romance']",NaN,NaN,"['Kit Connor', 'Sebastian Croft', 'Joe Locke',...",0,NaN,['Euros Lyn'],2
8978,Heartstopper,NaN,"['Drama', 'Romance']",NaN,NaN,[],0,NaN,['Euros Lyn'],2
7698,Hollywood Insider,(2018– ),['Talk-Show'],NaN,Behind the scenes of The Irishman.,"['Bobby Cannavale', 'Robert De Niro', 'Al Paci...",0,NaN,[],2
7699,Hollywood Insider,(2018– ),['Talk-Show'],NaN,Reactions at premiere of The Irishman.,"['Robert De Niro', 'Bo Dietl', 'Harvey Keitel'...",0,NaN,['Pritan Ambroase'],2
9117,I [Heart] Arlo,(2021– ),"['Animation', 'Short', 'Adventure']",NaN,NaN,"['Jennifer Coolidge', 'Flea', 'Brett Gelman', ...",0,NaN,['Nick Sumida'],2
9118,I [Heart] Arlo,(2021– ),"['Animation', 'Short', 'Adventure']",NaN,NaN,['Michael J. Woodard'],0,NaN,[],2
9178,Inside Man,NaN,"['Drama', 'Mystery', 'Thriller']",NaN,NaN,"['July Namir', 'David Tennant', 'Stanley Tucci...",0,NaN,['Paul McGuigan'],2
9238,Inside Man,NaN,"['Drama', 'Mystery', 'Thriller']",NaN,NaN,"['David Tennant', 'Stanley Tucci', 'Dolly Well...",0,NaN,['Paul McGuigan'],2
7266,Jack Whitehall: Travels with My Father,(2017– ),"['Documentary', 'Comedy']",7.2,Jack brings his father to California for a tou...,"['Jack Whitehall', 'Michael Whitehall', 'Antho...",128,50.0,['Leo McCrea'],2
7283,Jack Whitehall: Travels with My Father,(2017– ),"['Documentary', 'Comedy']",7.8,Jack and his father continue their tour of Ari...,"['Jack Whitehall', 'Michael Whitehall', 'Hilar...",114,60.0,['Leo McCrea'],2
7057,Legends of Tomorrow,(2016– ),"['Action', 'Adventure', 'Drama']",8.3,The Legends continue their hunt for pieces for...,"['Brandon Routh', 'Caity Lotz', 'Maisie Richar...",985,42.0,['Alexandra La Roche'],2
7058,Legends of Tomorrow,(2016– ),"['Action', 'Adventure', 'Drama']",8.9,"Ray plans a date night for him and Nora, but a...","['Brandon Routh', 'Caity Lotz', 'Maisie Richar...","1,220",42.0,['Ben Hernandez Bray'],2
9281,Master of None,(2015– ),"['Comedy', 'Drama']",5.8,"Now a bestselling author, Denise leads a quiet...","['Naomi Ackie', 'Lena Waithe', 'Aziz Ansari', ...","1,173",55.0,['Aziz Ansari'],2
9285,Master of None,(2015– ),"['Comedy', 'Drama']",5.7,A trip upstate leads to reflections on the pas...,"['Naomi Ackie', 'Lena Waithe', 'Sam Winner']",658,31.0,['Aziz Ansari'],2

If the description is NaN, there's no way to distinguish different episodes
Average out run_time, votes, rating
Concat genres, stars, directors
Use the older year started and newer year ended (do it after `years` is parsed)

Parse `years` with RegEx 
- split into a start and end field
- leave end as NaN if still running
- leave both as NaN if source is NaN
- correctly handle shows that only lasted one year

In [120]:
df.to_csv("./1.4.csv", index=False)